language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - rokmctkd6@gmail.com

before_deploy:
  - zip -r springboot-webservice-study *
  - mkdir -p deploy
  - mv springboot-webservice-study.zip deploy/springboot-webservice-study.zip

deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webservice-deploystudy # 6-3-3에서 생성한 S3 버킷
    key: springboot-webservice-study.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot-webservice-study # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-webservice-study-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: louisJu/springboot-webservice #Github 주소
      branch: master